### ISSUE TITLE
v0.1 prototype checklist

### ISSUE THREAD

**Issue by hwchen** [hwchen/tesseract#4]
## Roadmap checklist
- [x] json schema
- [x] metadata query (`/cubes`)
- [x] aggregation query
  - [x] basic query, no metadata or names
  - [x] plan aggregations roadmap (in sql vs in app)
  - [x] support cuts for members which are either string or not
  - [x] support joining on dim table for metadata
  - [x] support drilldowns of multi-level dims
  - [x] support cut by parent
  - [x] support parents in drilldown
  - [x] support inline dims
- [x] implement formatters
  - [x] csv
  - [x] jsonrecords
- [x] systemd `.service` file
---

**Comment by hwchen** [comment]
closed by https://github.com/hwchen/tesseract/commit/9e6a935ce67a13f6017f623379651e096083ae65
